apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: hoaiem22/udagram-api-user:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-configmap
          resources:
            limits:
              cpu: "500m"
              memory: "2048Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend-user
  name: backend-user
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend-user
  type: ClusterIP
status:
  loadBalancer: {}